"use client";

import React from "react";
import BookPageWrapper from "@/components/book/BookPageWrapper";

interface CoverPageProps {
    title: string;
    imageUrl: string | null;
    isBack?: boolean;
}

const CoverPage = React.forwardRef<HTMLDivElement, CoverPageProps>(
    ({ title, imageUrl, isBack = false }, ref) => {
        return (
            <div ref={ref} className="w-full h-full">
                <BookPageWrapper pagePosition={isBack ? "left" : "right"}>
                    <div className="w-full h-full relative overflow-hidden">
                        {/* Background image or gradient */}
                        {imageUrl ? (
                            <div
                                className="absolute inset-0 bg-cover bg-center"
                                style={{
                                    backgroundImage: `url(${imageUrl})`,
                                    filter: isBack ? "brightness(0.6) blur(1px)" : "brightness(0.75)",
                                }}
                            />
                        ) : (
                            <div className="absolute inset-0 bg-gradient-to-br from-orange-300 via-amber-200 to-orange-400" />
                        )}

                        {/* Overlay */}
                        <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-black/10" />

                        {/* Content */}
                        <div className="relative z-10 flex flex-col items-center justify-center h-full px-6 text-center">
                            {isBack ? (
                                <div className="space-y-3">
                                    <p className="text-4xl">📖</p>
                                    <p className="text-white/80 text-xs font-medium">
                                        Generated by
                                    </p>
                                    <p className="text-white text-base font-bold tracking-wide">
                                        Nusara
                                    </p>
                                    <p className="text-white/50 text-[10px]">
                                        Powered by Alibaba Cloud DashScope
                                    </p>
                                </div>
                            ) : (
                                <div className="space-y-3">
                                    <div className="w-12 h-0.5 bg-orange-400 rounded-full mx-auto" />
                                    <h1 className="text-2xl font-extrabold text-white drop-shadow-xl leading-tight font-serif">
                                        {title || "Untitled Story"}
                                    </h1>
                                    <div className="w-12 h-0.5 bg-orange-400 rounded-full mx-auto" />
                                    <p className="text-white/50 text-[10px] mt-3">
                                        Tap to begin →
                                    </p>
                                </div>
                            )}
                        </div>
                    </div>
                </BookPageWrapper>
            </div>
        );
    }
);

CoverPage.displayName = "CoverPage";
export default CoverPage;
